//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketPlaceEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string NumberCard { get; set; }
        public string DateCard { get; set; }
        public string CVC { get; set; }
        public Nullable<decimal> Balance { get; set; }
    
        public virtual User User { get; set; }
    }
}
